name: record_use
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.5.0-164.0.dev

dependencies:
  collection: ^1.18.0
  pub_semver: ^2.1.4

dev_dependencies:
  dart_flutter_team_lints: ^3.1.0
  lints: ^4.0.0
  test: ^1.24.0
