name: record_use
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.5.0-164.0.dev

dependencies:
  collection: ^1.18.0
  version: ^3.0.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  dart_flutter_team_lints: ^3.1.0
