name: test
permissions: read-all

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: [stable, dev]
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - uses: dart-lang/setup-dart@fedb1266e91cf51be2fdb382869461a434b920a3
        with:
          sdk: ${{matrix.sdk}}

      - run: dart pub get

      - run: dart analyze --fatal-infos

      - run: dart format --output=none --set-exit-if-changed .

      - run: dart test

      - name: Run Chrome tests - wasm
        run: dart test --platform chrome --compiler dart2wasm
        if: always() && matrix.sdk == 'dev'
